---
title: InvalidContextSignatureError
description: Error thrown when the context signature is invalid
slug: wallets/reference/account-kit/smart-contracts/src/classes/InvalidContextSignatureError
layout: reference
---

Defined in: [account-kit/smart-contracts/src/msca/errors.ts:16](https://github.com/alchemyplatform/aa-sdk/blob/da19afd63b0ba06a4de95b0d2d7871f64d546304/account-kit/smart-contracts/src/msca/errors.ts#L16)

Error thrown when the context signature is invalid

## Extends

- `BaseError`

## Constructors

### Constructor

```ts
new InvalidContextSignatureError(): InvalidContextSignatureError;
```

Defined in: [account-kit/smart-contracts/src/msca/errors.ts:18](https://github.com/alchemyplatform/aa-sdk/blob/da19afd63b0ba06a4de95b0d2d7871f64d546304/account-kit/smart-contracts/src/msca/errors.ts#L18)

#### Returns

`InvalidContextSignatureError`

#### Overrides

```ts
BaseError.constructor;
```

## Properties

<table>
  <thead>
    <tr>
      <th align="left">Property</th>
      <th align="left">Modifier</th>
      <th align="left">Type</th>
      <th align="left">Default value</th>
      <th align="left">Description</th>
      <th align="left">Overrides</th>
      <th align="left">Inherited from</th>
      <th align="left">Defined in</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        <a id="cause" /> `cause?`
      </td>

      <td>
        `public`
      </td>

      <td>
        `unknown`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.cause
        ```
      </td>

      <td>
        node\_modules/typescript/lib/lib.es2022.error.d.ts:26
      </td>
    </tr>

    <tr>
      <td>
        <a id="details" /> `details`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.details
        ```
      </td>

      <td>
        node\_modules/viem/\_types/errors/base.d.ts:19
      </td>
    </tr>

    <tr>
      <td>
        <a id="docspath" /> `docsPath?`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.docsPath
        ```
      </td>

      <td>
        node\_modules/viem/\_types/errors/base.d.ts:20
      </td>
    </tr>

    <tr>
      <td>
        <a id="message" /> `message`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.message
        ```
      </td>

      <td>
        node\_modules/typescript/lib/lib.es5.d.ts:1077
      </td>
    </tr>

    <tr>
      <td>
        <a id="metamessages" /> `metaMessages?`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`\[]
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.metaMessages
        ```
      </td>

      <td>
        node\_modules/viem/\_types/errors/base.d.ts:21
      </td>
    </tr>

    <tr>
      <td>
        <a id="name" /> `name`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `"InvalidContextSignatureError"`
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.name
        ```
      </td>

      <td>
        ‐
      </td>

      <td>
        [account-kit/smart-contracts/src/msca/errors.ts:17](https://github.com/alchemyplatform/aa-sdk/blob/da19afd63b0ba06a4de95b0d2d7871f64d546304/account-kit/smart-contracts/src/msca/errors.ts#L17)
      </td>
    </tr>

    <tr>
      <td>
        <a id="shortmessage" /> `shortMessage`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.shortMessage
        ```
      </td>

      <td>
        node\_modules/viem/\_types/errors/base.d.ts:22
      </td>
    </tr>

    <tr>
      <td>
        <a id="stack" /> `stack?`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.stack
        ```
      </td>

      <td>
        node\_modules/typescript/lib/lib.es5.d.ts:1078
      </td>
    </tr>

    <tr>
      <td>
        <a id="version" /> `version`
      </td>

      <td>
        `public`
      </td>

      <td>
        `string`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        ‐
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.version
        ```
      </td>

      <td>
        aa-sdk/core/dist/types/errors/base.d.ts:20
      </td>
    </tr>

    <tr>
      <td>
        <a id="stacktracelimit" /> `stackTraceLimit`
      </td>

      <td>
        `static`
      </td>

      <td>
        `number`
      </td>

      <td>
        `undefined`
      </td>

      <td>
        The `Error.stackTraceLimit` property specifies the number of stack frames
        collected by a stack trace (whether generated by `new Error().stack` or
        `Error.captureStackTrace(obj)`).

        The default value is `10` but may be set to any valid JavaScript number. Changes
        will affect any stack trace captured *after* the value has been changed.

        If set to a non-number value, or set to a negative number, stack traces will
        not capture any frames.
      </td>

      <td>
        ‐
      </td>

      <td>
        ```ts
        BaseError.stackTraceLimit
        ```
      </td>

      <td>
        node\_modules/@types/node/globals.d.ts:161
      </td>
    </tr>

  </tbody>
</table>

## Methods

### walk()

#### Call Signature

```ts
walk(): Error;
```

Defined in: node_modules/viem/\_types/errors/base.d.ts:26

##### Returns

`Error`

##### Inherited from

```ts
BaseError.walk;
```

#### Call Signature

```ts
walk(fn): null | Error;
```

Defined in: node_modules/viem/\_types/errors/base.d.ts:27

##### Parameters

<table>
  <thead>
    <tr>
      <th align="left">Parameter</th>
      <th align="left">Type</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `fn`
      </td>

      <td>
        (`err`) => `boolean`
      </td>
    </tr>

  </tbody>
</table>

##### Returns

`null` | `Error`

##### Inherited from

```ts
BaseError.walk;
```

---

### captureStackTrace()

```ts
static captureStackTrace(targetObject, constructorOpt?): void;
```

Defined in: node_modules/@types/node/globals.d.ts:145

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack; // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

<table>
  <thead>
    <tr>
      <th align="left">Parameter</th>
      <th align="left">Type</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `targetObject`
      </td>

      <td>
        `object`
      </td>
    </tr>

    <tr>
      <td>
        `constructorOpt?`
      </td>

      <td>
        `Function`
      </td>
    </tr>

  </tbody>
</table>

#### Returns

`void`

#### Inherited from

```ts
BaseError.captureStackTrace;
```

---

### prepareStackTrace()

```ts
static prepareStackTrace(err, stackTraces): any;
```

Defined in: node_modules/@types/node/globals.d.ts:149

#### Parameters

<table>
  <thead>
    <tr>
      <th align="left">Parameter</th>
      <th align="left">Type</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `err`
      </td>

      <td>
        `Error`
      </td>
    </tr>

    <tr>
      <td>
        `stackTraces`
      </td>

      <td>
        `CallSite`\[]
      </td>
    </tr>

  </tbody>
</table>

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

```ts
BaseError.prepareStackTrace;
```
