{"version":3,"file":"error.js","sourceRoot":"","sources":["error.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,SAAS,EAAE,MAAM,cAAc,CAAC;AAEzC,MAAM,OAAO,mBAAoB,SAAQ,SAAS;IAEhD;QACE,KAAK,CAAC,2BAA2B,EAAE;YACjC,QAAQ,EAAE,wBAAwB;SACnC,CAAC,CAAC;QAJI;;;;mBAAO,qBAAqB;WAAC;IAKtC,CAAC;CACF;AAED;;GAEG;AACH,MAAM,OAAO,gBAAiB,SAAQ,SAAS;IAA/C;;QACW;;;;mBAAO,kBAAkB;WAAC;IACrC,CAAC;CAAA;AAED;;;GAGG;AACH,MAAM,OAAO,mBAAoB,SAAQ,SAAS;IAGhD;;;OAGG;IACH;QACE,KAAK,CAAC,iBAAiB,CAAC,CAAC;QAPlB;;;;mBAAO,qBAAqB;WAAC;IAQtC,CAAC;CACF","sourcesContent":["import { BaseError } from \"@aa-sdk/core\";\n\nexport class OAuthProvidersError extends BaseError {\n  override name = \"OAuthProvidersError\";\n  constructor() {\n    super(\"OAuth providers not found\", {\n      docsPath: \"/react/getting-started\",\n    });\n  }\n}\n\n/**\n * This error is thrown when an error occurs during the OAuth login flow.\n */\nexport class OauthFailedError extends BaseError {\n  override name = \"OauthFailedError\";\n}\n\n/**\n * This error is thrown when the OAuth flow is cancelled because the auth popup\n * window was closed.\n */\nexport class OauthCancelledError extends BaseError {\n  override name = \"OauthCancelledError\";\n\n  /**\n   * Constructor for initializing an error indicating that the OAuth flow was\n   * cancelled.\n   */\n  constructor() {\n    super(\"OAuth cancelled\");\n  }\n}\n"]}